
 SELECT C_NAME, C_ADDRESS, C_PHONE
 FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER"
 WHERE C_NATIONKEY IN (8, 24)
 UNION
 SELECT C_NAME, C_ADDRESS, C_PHONE
 FROM "SNOWFLAKE_SAMPLE_DATA"."TPCH_SF1"."CUSTOMER"
 WHERE C_MKTSEGMENT = 'AUTOMOBILE';